resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
- env.yaml
- manager_webhook_patch.yaml
images:
- name: controller
  newName: localhost:5001/aim/ingress-node-firewall
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
